version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "npm"
    directory: "/packages/envex"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "npm"
    directory: "/examples/nextjs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "npm"
    directory: "/configs/eslint"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "npm"
    directory: "/configs/prettier"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "npm"
    directory: "/configs/semantic-release"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "auto-update"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"